preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_urls: true
  remove_mentions: true
  remove_numbers: false
  normalize_whitespace: true
  remove_stopwords: false
  min_word_length: 2
  max_word_length: 50
  handle_emojis: remove
vectorizer:
  type: tfidf
  max_features: 10000
  ngram_range: [1, 2]
  min_df: 2
  max_df: 0.95
  use_char_ngrams: false
  char_ngram_range: [3, 5]
  sublinear_tf: true
model:
  type: logistic
  use_class_weights: true
  calibration_method: null
  max_iter: 1000
  random_state: 42
  n_estimators: 100
training:
  n_splits: 5
  stratify: true
  validation_size: 0.2
  early_stopping: false
  patience: 3
performance_mode: standard
output_dir: runs
competition_name: jigsaw-agile-community-rules
debug: false
