version: "3.1.0"
seed: 42
performance_mode: balanced
n_splits_max: 5
min_group_k_folds: 3
max_tfidf_features: 100000
calibration_enabled: true
calibration_method: isotonic
epsilon_prob_clip: 1e-6
n_ece_bins: 10
top_n_features_display: 15
text_columns:
  - body
  - rule
  - subreddit
  - positive_example_1
  - positive_example_2
  - negative_example_1
  - negative_example_2
text_prefixes:
  body: "comment:"
  rule: "rule:"
  subreddit: "subreddit: r/"
  positive_example_1: "positive1:"
  positive_example_2: "positive2:"
  negative_example_1: "negative1:"
  negative_example_2: "negative2:"
label_column: rule_violation
id_column: row_id
group_column: rule
tfidf_word_params:
  strip_accents: unicode
  lowercase: true
  ngram_range: [1, 2]
  min_df: 3
  max_df: 0.95
  sublinear_tf: true
tfidf_char_params:
  strip_accents: null
  lowercase: false
  analyzer: char
  ngram_range: [3, 5]
  min_df: 3
  max_df: 0.95
  sublinear_tf: true
large_data_threshold: 10000
batch_size: 2000
n_jobs: -1
early_stopping: true
patience: 5
tol: 0.0001
use_sgd: false
normalizer: regex
vectorizer: tfidf
vectorizer_mode: word_char
dimensionality_reduction: null
dimensionality_reduction_components: null
explained_variance: null
cache_dir: runs
cache_enabled: true
